Fix leaking error messages to client
This patch replaces all perror() APIs with ERR().  The former sends the
error message to STDERR, which like STDOUT is sent to the client.

Found when debugging the following error found by https://ftptest.net

      Error: Line feed received without preceding carriage return

Seems uftpd fails accept() sometimes and use perror() to signal error,
which is interpreted by ftptest.net as a line ending error.

Signed-off-by: Joachim Nilsson <troglobit@gmail.com>